# Site settings
title:     Zizhen Zuo - Creative Designer & Developer
email:     hjsfzzz@gmail.com
description: "I'm Zizhen Zuo (左子祯), a creative designer and developer form China."
keywords: "左子祯, zizhen, zizhen zuo, zizhenzuo, china designer"
author:   "Zizhen Zuo"
url: "https://zizhenzuo.com"
baseurl: ""
name: zizhen

# # SCSS settings
# sass:
#   sass_dir: assets/stylesheets/_libs

# SNS settings
RSS: ture
dribbble_username:  zuonx
behance_username:   zuonx
pinterest_username: zuozizhen
github_username:    zuonx
instagram_username: zuozizhen
zhihu_username:     ZiJen

# Paginate settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 7
paginate_path: "blog/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true

# plugins
plugins: [jekyll-paginate]

stylus:
  compress: true
  path: assets/stylesheets

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# Analytics settings

ga_track_id: 'UA-111351144-1'
